name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Dump env for debug (TEMP)
        run: printenv

      - name: Build backend JAR
        run: |
          cd backend
          ./mvnw clean package -DskipTests

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/courier-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/courier-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/courier-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/courier-frontend:latest